### ISSUE TITLE
DataMiner Compute Requirements

### ISSUE THREAD

**Issue by thomasgunkel** [SkylineCommunications/dataminer-docs#1039]
Can you add a link to latest DataMiner requirements? https://community.dataminer.services/dataminer-compute-requirements/?hilite=compute+requirements - on the installing DataMiner Agents docs page: https://docs.dataminer.services/user-guide/Advanced_Functionality/DataMiner_Agents/Installing_a_DataMiner_Agent.html

**Comment by MariekeGO** [comment]
There already is a link to the latest requirements on that page:
![image](https://user-images.githubusercontent.com/94605575/218395077-f2030fa2-05da-4ccc-8304-28afe2b73da8.png)
Did you mean some other page than the one you linked to?
