### ISSUE TITLE
IConnection Link not working

### ISSUE THREAD

**Issue by miguel-slc** [SkylineCommunications/dataminer-docs#1327]
When clicking on this link: https://docs.dataminer.services/develop/api/types/Skyline.DataMiner.Net.IConnection.html
(e.g. available in Method [GetDms](https://docs.dataminer.services/develop/api/types/Skyline.DataMiner.Core.DataMinerSystem.Common.ConnectionInterfaceExtensions.GetDms.html)), the page is not found (404)

**Comment by MariekeGO** [comment]
Quick update: Pedro is looking into this, but it will probably take a while to get it fixed.
