### ISSUE TITLE
Incorrect information about WinPCap

### ISSUE THREAD

**Issue by Black-Lung** [SkylineCommunications/dataminer-docs#1369]
In the page "Installing DataMiner using the DataMiner Installer" under the section "Custom DataMiner installation", under point 5 pertaining to WinPCap, it is mentioned "On systems intended for DataMiner Failover, install WinPcap by clicking Install WinPcap" whereas in the customer installer, that option is disabled. Attached photo.
![WinPCap](https://user-images.githubusercontent.com/99705701/233548450-2733ffb8-7daf-4fb3-98ab-f85b3ef09637.png)

**Comment by MariekeGO** [comment]
See also https://community.dataminer.services/question/unable-to-select-winpcap-with-10-2-installer/

**Comment by MariekeGO** [comment]
PR #1377 has been created to add this info. Note that this will first need to be verified by QA before we can merge it.
