### ISSUE TITLE
Lack of examples when using the Dashboards URL feed option

### ISSUE THREAD

**Issue by brmdias** [SkylineCommunications/dataminer-docs#1489]
This page is explaining how to use the feature but it is missing concrete examples so that users can mimic.
This is slowing down its comprehension and adoption.

https://github.com/SkylineCommunications/dataminer-docs/blob/main/user-guide/Advanced_Modules/Dashboards_app/Using_dashboard_feeds/Specifying_data_input_in_a_dashboard_URL.md/#L1

**Comment by EdithLansens** [comment]
- [Pull request #1497](https://github.com/SkylineCommunications/dataminer-docs/pull/1497): An example of how to pass the data using a JSON object in the URL has been added to give readers a more concrete idea of what this feature looks like.
- A [collaboration task](https://collaboration.dataminer.services/squads/69/list/task/212323) has been created to add more examples in the future, including screenshots of the result in the Dashboards app.
