### ISSUE TITLE
machineName

### ISSUE THREAD

**Issue by Scheddy1** [SkylineCommunications/dataminer-docs#1567]
Please add information for <Agent machineName="">.
Because the machineName is the netbios name of the server and limited to 15 characters. This is a crucial information.

**Comment by MariekeGO** [comment]
@Scheddy1 Something seems to be missing in your comment. Could you clarify which section of the documentation this is about?

**Comment by MariekeGO** [comment]
@Scheddy1 Could it be that you mean the [InstallConfiguration.xml file](https://docs.dataminer.services/user-guide/Getting_started/Installing_a_DMA/Unattended_DM_installation.html#unattended-installation-configuration-file), for unattended DataMiner installation? That's the only place where I can find the machineName tag.

**Comment by Scheddy1** [comment]
@MariekeGO in the InstallConfiguration file it needs to be specified that it's only the netbios name with 15 characters and the computer name.
For the dms.xml same information is missing. Should be copied. 
This is for example in our dms.xml:
`<DMS>
	<Failover configVersion="2" active="true" type="manual" lastConfigChange="2021-09-20 05:33:08" partialConfig="false" bruteForceToOffline="false">
		<State state="online" stateBeforeShutdown="online" lastStateChange="2023-05-30 15:23:04" lastOnlineTime="2023-05-30 15:23:04"></State>
		<VirtualIPs>
			<VirtualIP address="XXX" mask="255.255.255.0" nic="1"></VirtualIP>
			<VirtualIP address="" mask="" nic="2"></VirtualIP>
		</VirtualIPs>
		<Agents>
			<Agent machineName="NETBIOS NAME">
				<LocalIP nic="1" address="" mask="255.255.255.0"></LocalIP>
				<LocalIP nic="2" address="" mask=""></LocalIP>
				<DestinationSyncIP></DestinationSyncIP>
				<HeartBeat destinationIP="XXX" interval="20000" allowedFailures="6" options="slnetonly"></HeartBeat>
			</Agent>
			<Agent machineName="NETBIOS NAME">
				<LocalIP nic="1" address="" mask="255.255.255.0"></LocalIP>
				<LocalIP nic="2" address="" mask=""></LocalIP>
				<DestinationSyncIP></DestinationSyncIP>
				<HeartBeat destinationIP="XXX" interval="20000" allowedFailures="6" options="slnetonly"></HeartBeat>
			</Agent>
		</Agents>
		<FailoverType>VirtualIP</FailoverType>
	</Failover>
</DMS>`
