### ISSUE TITLE
InterApp example code mentioned, but not found in the linked resource

### ISSUE THREAD

**Issue by bhole1** [SkylineCommunications/dataminer-docs#1811]
Hi, I'm getting familiar with InterApp so I've been reading the [InterApp documentation](https://docs.dataminer.services/develop/devguide/ClassLibrary/ClassLibraryInterAppClasses.html). 

Right under the _Getting started_ section there is a note stating that a sample protocol (SLC SDF Inter App Calls) can be found in the [Protocol Development Guide Companion Files ](https://community.dataminer.services/documentation/protocol-development-guide-companion-files/) on dojo.

I downloaded the zipped file and I couldn't find the InterApp example. Could you please verify this?

**Comment by spetebroodt** [comment]
Hi Benjamin. I passed on the message. We'll check the zip file asap.

**Comment by spetebroodt** [comment]
Hi Benjamin. The companion files zip file has been updated. It should now also contain the InterApp example. Can you have a look?

**Comment by bhole1** [comment]
Hello José,

Yes, now I see the sample protocol.

Thank you.

***@***.***<https://skyline.be/learn/events>


Benjamin Hodžić | System Developer
Email ***@***.******@***.***>

Skyline Communications
Avaz Twist Tower | Tešanjska 24A | Sarajevo 71000 | Bosnia and Herzegovina
www.skyline.be<https://www.skyline.be/>

***@***.***<https://skyline.be/>


***@***.******@***.***>
***@***.***<https://community.dataminer.services/?utm_source=signature&utm_medium=email&utm_campaign=icon>
***@***.***<https://www.linkedin.com/company/skyline-communications>
***@***.***<https://www.youtube.com/user/SkylineCommu>
***@***.***<https://www.facebook.com/SkylineCommunications/>
***@***.***<https://www.instagram.com/skyline.dataminer/>
***@***.***<https://skyline.be/skyline/awards?utm_source=signature&utm_medium=email&utm_campaign=icon>

***@***.***
