### ISSUE TITLE
Protocol.ExportRules.ExportRule whereTag/whereValue examples

### ISSUE THREAD

**Issue by TomW-Skyline** [SkylineCommunications/dataminer-docs#214]
https://github.com/SkylineCommunications/dataminer-docs/blob/main/develop/schemadoc/Protocol/Protocol.ExportRules.ExportRule-whereTag.md
https://github.com/SkylineCommunications/dataminer-docs/blob/main/develop/schemadoc/Protocol/Protocol.ExportRules.ExportRule-whereValue.md

Examples on both pages are probably not correct. The examples don't use the "whereTag" and "whereValue" attributes.

**Comment by MariekeGO** [comment]
@PedroDebevere could you look into this?

**Comment by PedroDebevere** [comment]
The example is indeed a better fit on the regex attribute page. OK to merge the provided PR.
