### ISSUE TITLE
Missing video about conditional alarming

### ISSUE THREAD

**Issue by TomW-Skyline** [SkylineCommunications/dataminer-docs#3189]
At the bottom of the following page there is a link to a video about conditional monitoring in alarm templates: https://docs.dataminer.services/user-guide/Basic_Functionality/Protocols_and_templates/Alarm_templates/Configuring_alarm_templates/Using_conditions_in_an_alarm_template.html.
However, the video behind that link seems to be removed.

**Comment by MariekeGO** [comment]
There was a temporary issue with the videos on Dojo, but this should now be fixed.
