### ISSUE TITLE
Soft-launch page is too long

### ISSUE THREAD

**Issue by brmdias** [SkylineCommunications/dataminer-docs#708]
[Soft-launch page ](https://docs.dataminer.services/user-guide/Reference/Soft-launch_options/SoftLaunchOptions.html) is too long.
Can we add a list with hyperlink at the start, so the user can easily navigate to the soft-launch option he's looking for?

**Comment by MariekeGO** [comment]
To easily navigate to a specific option, you can use the table of contents on the right side of the page. However, As there is rather a lot of content on this page right now, this is not as user-friendly as it could be at the moment, so we'll look into splitting up this page into several subpages.

![image](https://user-images.githubusercontent.com/94605575/201039237-ebd3458f-d2d4-4f7e-ab1f-4f6070273bfb.png)

**Comment by MariekeGO** [comment]
Update: The page has now been divided into several subpages. You can find an overview of the different options [here](https://docs.dataminer.services/user-guide/Reference/Soft-launch_options/Overview_of_Soft_Launch_Options.html) and use the table of contents on the right to immediately navigate to a specific option.
