### ISSUE TITLE
The Sharing page has a broken link reference to Sharing_a_dashboard 

### ISSUE THREAD

**Issue by AlexJBSilva** [SkylineCommunications/dataminer-docs#905]
In the Sharing page https://shares.dataminer.services, the link for Sharing_a_dashboard is outdated:
https://docs.dataminer.services/user-guide/Advanced_Modules/Dashboards_app/Creating_and_configuring_dashboards/Sharing_a_dashboard.html

It should be updated to https://docs.dataminer.services/user-guide/Advanced_Modules/Dashboards_app/Sharing_a_dashboard.html

(Path changed in 4e5eec60432c67a8e58268704e38f95c5f920a52)

**Comment by MariekeGO** [comment]
Thanks for letting us know! I'll take this up with the cloud team so they can replace the link.

**Comment by MariekeGO** [comment]
This should now be fixed. Note that you may need to clear your cache to see the updated page.
